trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureRmWebAppDeployment@4
    inputs:
      azureSubscription: '<Service_Connection_Name>'
      appType: 'webApp'
      appName: '<App_Service_Name>'
      packageForLinux: $(System.DefaultWorkingDirectory)/**/*.zip
